In [84]:
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import tensorflow as tf
import numpy as np 

file_path = './dataset/poetry.txt'

with open(file_path, "r", encoding='utf-8') as f:
        poetry_list = f.readlines()
        print(type(poetry_list))
        print(poetry_list[0])

<class 'list'>
首春:寒随穷律变，春逐鸟声开。初风飘带柳，晚雪间花梅。碧林青旧竹，绿沼翠新苔。芝田初雁去，绮树巧莺来。



In [85]:
words = sorted(set(''.join(poetry_list)+' '))   # set 去重
print(words)

['\n', ' ', '(', ')', '2', '3', '4', '6', '7', '8', '9', ':', ';', 'C', 'D', 'F', 'M', 'X', '\\', '_', 'b', 'c', 'd', 'f', 'g', 'h', 'j', 'l', 'o', 'p', 'q', 'z', 'í', 'ó', 'ā', 'ē', 'ī', 'ń', 'ū', 'ǖ', 'ɡ', '“', '”', '…', '─', '□', '、', '。', '々', '《', '》', '【', '】', 'ヨ', '一', '丁', '七', '万', '丈', '三', '上', '下', '不', '与', '丐', '丑', '专', '且', '丕', '世', '丘', '丙', '业', '丛', '东', '丝', '丞', '两', '严', '丧', '个', '丫', '中', '丰', '丱', '串', '丳', '临', '丸', '丹', '为', '主', '丽', '举', '乂', '乃', '久', '么', '义', '之', '乌', '乍', '乎', '乏', '乐', '乔', '乖', '乘', '乙', '九', '乞', '也', '习', '乡', '书', '买', '乱', '乳', '乾', '了', '予', '争', '事', '二', '于', '亏', '云', '互', '五', '井', '亘', '亚', '些', '亟', '亡', '亢', '交', '亥', '亦', '产', '亨', '亩', '享', '京', '亭', '亮', '亲', '亳', '亵', '亶', '亸', '亹', '人', '亻', '亿', '什', '仁', '仄', '仅', '仆', '仇', '今', '介', '仍', '从', '仑', '仓', '仔', '仕', '他', '仗', '付', '仙', '仝', '仞', '仡', '代', '令', '以', '仪', '仰', '仲', '仳', '价', '任', '份', '仿', '企', '伉', '伊', '伋', '伍', '伎', '伏', '伐', '休', '众', '优', '伙', '会

In [86]:
int_to_word = {i: word for i, word in enumerate(words)}
int_to_word

{0: '\n',
 1: ' ',
 2: '(',
 3: ')',
 4: '2',
 5: '3',
 6: '4',
 7: '6',
 8: '7',
 9: '8',
 10: '9',
 11: ':',
 12: ';',
 13: 'C',
 14: 'D',
 15: 'F',
 16: 'M',
 17: 'X',
 18: '\\',
 19: '_',
 20: 'b',
 21: 'c',
 22: 'd',
 23: 'f',
 24: 'g',
 25: 'h',
 26: 'j',
 27: 'l',
 28: 'o',
 29: 'p',
 30: 'q',
 31: 'z',
 32: 'í',
 33: 'ó',
 34: 'ā',
 35: 'ē',
 36: 'ī',
 37: 'ń',
 38: 'ū',
 39: 'ǖ',
 40: 'ɡ',
 41: '“',
 42: '”',
 43: '…',
 44: '─',
 45: '□',
 46: '、',
 47: '。',
 48: '々',
 49: '《',
 50: '》',
 51: '【',
 52: '】',
 53: 'ヨ',
 54: '一',
 55: '丁',
 56: '七',
 57: '万',
 58: '丈',
 59: '三',
 60: '上',
 61: '下',
 62: '不',
 63: '与',
 64: '丐',
 65: '丑',
 66: '专',
 67: '且',
 68: '丕',
 69: '世',
 70: '丘',
 71: '丙',
 72: '业',
 73: '丛',
 74: '东',
 75: '丝',
 76: '丞',
 77: '两',
 78: '严',
 79: '丧',
 80: '个',
 81: '丫',
 82: '中',
 83: '丰',
 84: '丱',
 85: '串',
 86: '丳',
 87: '临',
 88: '丸',
 89: '丹',
 90: '为',
 91: '主',
 92: '丽',
 93: '举',
 94: '乂',
 95: '乃',
 96: '久',
 97: '么',
 98: '义',
 99: '之',
 100: '乌

In [87]:
word_to_int = {v: k for k, v in int_to_word.items()}
word_to_int

{'\n': 0,
 ' ': 1,
 '(': 2,
 ')': 3,
 '2': 4,
 '3': 5,
 '4': 6,
 '6': 7,
 '7': 8,
 '8': 9,
 '9': 10,
 ':': 11,
 ';': 12,
 'C': 13,
 'D': 14,
 'F': 15,
 'M': 16,
 'X': 17,
 '\\': 18,
 '_': 19,
 'b': 20,
 'c': 21,
 'd': 22,
 'f': 23,
 'g': 24,
 'h': 25,
 'j': 26,
 'l': 27,
 'o': 28,
 'p': 29,
 'q': 30,
 'z': 31,
 'í': 32,
 'ó': 33,
 'ā': 34,
 'ē': 35,
 'ī': 36,
 'ń': 37,
 'ū': 38,
 'ǖ': 39,
 'ɡ': 40,
 '“': 41,
 '”': 42,
 '…': 43,
 '─': 44,
 '□': 45,
 '、': 46,
 '。': 47,
 '々': 48,
 '《': 49,
 '》': 50,
 '【': 51,
 '】': 52,
 'ヨ': 53,
 '一': 54,
 '丁': 55,
 '七': 56,
 '万': 57,
 '丈': 58,
 '三': 59,
 '上': 60,
 '下': 61,
 '不': 62,
 '与': 63,
 '丐': 64,
 '丑': 65,
 '专': 66,
 '且': 67,
 '丕': 68,
 '世': 69,
 '丘': 70,
 '丙': 71,
 '业': 72,
 '丛': 73,
 '东': 74,
 '丝': 75,
 '丞': 76,
 '两': 77,
 '严': 78,
 '丧': 79,
 '个': 80,
 '丫': 81,
 '中': 82,
 '丰': 83,
 '丱': 84,
 '串': 85,
 '丳': 86,
 '临': 87,
 '丸': 88,
 '丹': 89,
 '为': 90,
 '主': 91,
 '丽': 92,
 '举': 93,
 '乂': 94,
 '乃': 95,
 '久': 96,
 '么': 97,
 '义': 98,
 '之': 99,
 '乌': 10

In [88]:
to_int = lambda word: word_to_int.get(word)
to_int


<function __main__.<lambda>(word)>

In [89]:
poetry_vectors = [list(map(to_int, poetry)) for poetry in poetry_list]
poetry_vectors

[[7206,
  2493,
  11,
  1417,
  6936,
  4442,
  1801,
  703,
  7640,
  2493,
  6461,
  7466,
  1158,
  1733,
  47,
  519,
  7138,
  7147,
  1647,
  2719,
  7640,
  2522,
  6976,
  6847,
  5254,
  2788,
  47,
  4278,
  2664,
  7018,
  2463,
  4494,
  7640,
  4842,
  3144,
  4970,
  2435,
  5273,
  47,
  5242,
  3945,
  519,
  6957,
  688,
  7640,
  4827,
  2734,
  1612,
  5383,
  2637,
  47,
  0],
 [519,
  2534,
  5435,
  2532,
  11,
  2522,
  7002,
  5017,
  5164,
  1870,
  7640,
  519,
  2534,
  1753,
  718,
  898,
  47,
  2461,
  2510,
  4064,
  5254,
  5226,
  7640,
  7138,
  574,
  629,
  2664,
  4970,
  47,
  3092,
  7370,
  6219,
  62,
  734,
  7640,
  994,
  7466,
  1158,
  6426,
  1735,
  47,
  1411,
  5919,
  643,
  6467,
  4988,
  7640,
  4203,
  120,
  3680,
  1171,
  1829,
  47,
  0],
 [519,
  1167,
  11,
  54,
  2599,
  2493,
  1167,
  2385,
  7640,
  6938,
  1174,
  7466,
  5254,
  6412,
  47,
  6892,
  6891,
  3310,
  3223,
  724,
  7640,
  2517,
  1170,
  6652,
  6371,


In [90]:
batch_size = 5
batches = poetry_vectors[0: batch_size]
x_batch = np.full((batch_size, max(map(len, batches))), word_to_int[' '], np.int32)
print(batches)
print(x_batch.shape)
x_batch

[[7206, 2493, 11, 1417, 6936, 4442, 1801, 703, 7640, 2493, 6461, 7466, 1158, 1733, 47, 519, 7138, 7147, 1647, 2719, 7640, 2522, 6976, 6847, 5254, 2788, 47, 4278, 2664, 7018, 2463, 4494, 7640, 4842, 3144, 4970, 2435, 5273, 47, 5242, 3945, 519, 6957, 688, 7640, 4827, 2734, 1612, 5383, 2637, 47, 0], [519, 2534, 5435, 2532, 11, 2522, 7002, 5017, 5164, 1870, 7640, 519, 2534, 1753, 718, 898, 47, 2461, 2510, 4064, 5254, 5226, 7640, 7138, 574, 629, 2664, 4970, 47, 3092, 7370, 6219, 62, 734, 7640, 994, 7466, 1158, 6426, 1735, 47, 1411, 5919, 643, 6467, 4988, 7640, 4203, 120, 3680, 1171, 1829, 47, 0], [519, 1167, 11, 54, 2599, 2493, 1167, 2385, 7640, 6938, 1174, 7466, 5254, 6412, 47, 6892, 6891, 3310, 3223, 724, 7640, 2517, 1170, 6652, 6371, 3570, 47, 836, 5383, 3704, 829, 3027, 7640, 2929, 75, 2995, 4902, 1177, 47, 3829, 7307, 430, 1786, 2252, 7640, 4833, 4791, 5332, 4779, 6431, 47, 4278, 7413, 1951, 2826, 269, 7640, 3783, 3635, 5188, 2954, 542, 47, 228, 1821, 3105, 6891, 1163, 7640, 1242, 1166

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [94]:
for row in range(batch_size): 
    x_batch[row, :len(batches[row])] = batches[row]
x_batch # 作为输入

array([[7206, 2493,   11, 1417, 6936, 4442, 1801,  703, 7640, 2493, 6461,
        7466, 1158, 1733,   47,  519, 7138, 7147, 1647, 2719, 7640, 2522,
        6976, 6847, 5254, 2788,   47, 4278, 2664, 7018, 2463, 4494, 7640,
        4842, 3144, 4970, 2435, 5273,   47, 5242, 3945,  519, 6957,  688,
        7640, 4827, 2734, 1612, 5383, 2637,   47,    0,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
       [ 519, 2534, 5435, 2532,   11, 2522, 7002, 5017, 5164, 1870, 7640,
         519, 2534, 1753,  718,  898,   47, 2461, 2510, 4064, 5254, 5226,
        7640, 7138,  574,  629, 2664, 4970,   47, 3092, 7370, 6219,   62,
         734, 7640,  994, 7466, 1158, 6426, 1735,   47, 1411, 5919,  643,
        6467, 4988, 7640, 4203,  120, 3680, 1171, 1829,   47,    0,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,

In [93]:
y_batch = np.copy(x_batch)
y_batch[:, :-1], y_batch[:, -1] = x_batch[:, 1:], x_batch[:, 0]
y_batch  # 作为标签

array([[2493,   11, 1417, 6936, 4442, 1801,  703, 7640, 2493, 6461, 7466,
        1158, 1733,   47,  519, 7138, 7147, 1647, 2719, 7640, 2522, 6976,
        6847, 5254, 2788,   47, 4278, 2664, 7018, 2463, 4494, 7640, 4842,
        3144, 4970, 2435, 5273,   47, 5242, 3945,  519, 6957,  688, 7640,
        4827, 2734, 1612, 5383, 2637,   47,    0,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1, 7206],
       [2534, 5435, 2532,   11, 2522, 7002, 5017, 5164, 1870, 7640,  519,
        2534, 1753,  718,  898,   47, 2461, 2510, 4064, 5254, 5226, 7640,
        7138,  574,  629, 2664, 4970,   47, 3092, 7370, 6219,   62,  734,
        7640,  994, 7466, 1158, 6426, 1735,   47, 1411, 5919,  643, 6467,
        4988, 7640, 4203,  120, 3680, 1171, 1829,   47,    0,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,

In [ ]:
input_x = tf.placeholder(tf.int32, shape=(batch_size, None), name='input_x')
target_y = tf.placeholder(tf.int32, shape=(batch_size, None), name='target_y')

keep_prob = tf.placeholder(tf.float32, name='keep_prob')

In [ ]:
rnn_size = 128  # 隐藏层的数量
word_len =  poetry_list# 所出现字符的数量

embedding = tf.get_variable('embedding', [word_len, rnn_size])
lstm_inputs = tf.nn.embedding_lookup(embedding, inputs)


In [ ]:
def embedding_variable(inputs, rnn_size, word_len):
        with tf.variable_scope('embedding'):
            # 这里选择使用cpu进行embedding
            with tf.device("/cpu:0"):
                # 默认使用'glorot_uniform_initializer'初始化，来自源码说明:
                # If initializer is `None` (the default), the default initializer passed in
                # the variable scope will be used. If that one is `None` too, a
                # `glorot_uniform_initializer` will be used.
                # 这里实际上是根据字符数量分别生成state_size长度的向量
                embedding = tf.get_variable('embedding', [word_len, rnn_size])
                # 根据inputs序列中每一个字符对应索引 在embedding中寻找对应向量,即字符转为连续向量:[字]==>[1]==>[0,1,0]
                lstm_inputs = tf.nn.embedding_lookup(embedding, inputs)
        return lstm_inputs

